[versions]
agp = "9.0.0"
androidGpxParser = "2.3.1"
androidImageCropper = "4.7.0"
coilCompose = "2.7.0"
converterGson = "3.0.0"
core = "1.17.0"
datastorePreferences = "1.1.7"
easycrop = "0.1.1"
exifinterface = "1.4.2"
fragmentKtx = "1.8.9"
kotlin = "2.2.10"
lifecycleViewmodelCompose = "2.9.2"
materialIconsExtended = "1.7.8"
navigationCompose = "2.9.3"
playServicesLocation = "21.3.0"
playServicesWearable = "19.0.0"
composeBom = "2025.08.00"
composeMaterial = "1.4.1"
composeFoundation = "1.4.1"
runtime = "1.9.0"
roomRuntime = "2.7.2"
runtimeLivedata = "1.9.0"
wear = "1.3.0"
wearOngoing = "1.0.0"
wearToolingPreview = "1.0.0"
activityCompose = "1.10.1"
coreSplashscreen = "1.0.1"
composeMaterial3 = "1.5.0-rc02"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.2"
appcompat = "1.7.1"
material = "1.12.0"
material3Android = "1.3.2"

[libraries]
android-gpx-parser = { module = "com.github.ticofab:android-gpx-parser", version.ref = "androidGpxParser" }
easycrop = { module = "io.github.mr0xf00:easycrop", version.ref = "easycrop" }
exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version = "2.1" }
coil = { module = "io.coil-kt:coil", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilCompose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core = { module = "androidx.core:core", version.ref = "core" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converterGson" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
runtime = { module = "androidx.compose.runtime:runtime", version.ref = "runtime" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "runtimeLivedata" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
compose-foundation = { group = "androidx.wear.compose", name = "compose-foundation", version.ref = "composeFoundation" }
wear = { module = "androidx.wear:wear", version.ref = "wear" }
wear-ongoing = { module = "androidx.wear:wear-ongoing", version.ref = "wearOngoing" }
wear-tooling-preview = { group = "androidx.wear", name = "wear-tooling-preview", version.ref = "wearToolingPreview" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

